// Path planner: click waypoints on the field, edit them, simulate the
// route, and generate the equivalent C++ for the real robot.

import type { Chassis } from '../lib/chassis.ts';
import type { FieldView } from './field.ts';

export interface PathPoint {
  x: number;
  y: number;
  /** how the robot reaches this point (ignored for the start point) */
  kind: 'point' | 'pose';
  /** arrival heading, compass degrees (start heading for the first point) */
  theta: number;
  forwards: boolean;
  maxSpeed: number;
}

const HIT_RADIUS_PX = 11;

function fmt(n: number): string {
  const r = Math.round(n * 10) / 10;
  return Number.isInteger(r) ? String(r) : r.toFixed(1);
}

export class Planner {
  points: PathPoint[] = [];
  timeout = 4000;
  active = false;

  /** notified whenever the path changes (app re-renders nothing; we do) */
  onSimulate: (() => void) | null = null;

  private field: FieldView;
  private listEl: HTMLElement;
  private codeEl: HTMLElement;
  private dragIndex = -1;
  private dragged = false;

  constructor(field: FieldView, listEl: HTMLElement, codeEl: HTMLElement) {
    this.field = field;
    this.listEl = listEl;
    this.codeEl = codeEl;
    this.bindCanvas();
    this.refresh();
  }

  // ------------------------------------------------------------------
  // canvas interaction: add, drag, delete
  // ------------------------------------------------------------------

  private canvasPoint(e: MouseEvent): [number, number] {
    const rect = this.field.canvas.getBoundingClientRect();
    return [e.clientX - rect.left, e.clientY - rect.top];
  }

  private hitTest(px: number, py: number): number {
    for (let i = this.points.length - 1; i >= 0; i--) {
      const [x, y] = this.field.toPx(this.points[i].x, this.points[i].y);
      if (Math.hypot(px - x, py - y) <= HIT_RADIUS_PX) return i;
    }
    return -1;
  }

  private bindCanvas(): void {
    const canvas = this.field.canvas;

    canvas.addEventListener('mousedown', (e) => {
      if (!this.active || e.button !== 0) return;
      const [px, py] = this.canvasPoint(e);
      this.dragIndex = this.hitTest(px, py);
      this.dragged = false;
    });

    canvas.addEventListener('mousemove', (e) => {
      if (!this.active || this.dragIndex < 0) return;
      const [px, py] = this.canvasPoint(e);
      const [x, y] = this.field.toField(px, py);
      const p = this.points[this.dragIndex];
      p.x = snap(clampField(x));
      p.y = snap(clampField(y));
      this.dragged = true;
      this.updateRowInputs(this.dragIndex);
      this.renderCode();
    });

    window.addEventListener('mouseup', () => {
      this.dragIndex = -1;
    });

    canvas.addEventListener('click', (e) => {
      if (!this.active) return;
      const [px, py] = this.canvasPoint(e);
      // a click that ended a drag, or landed on an existing point, adds nothing
      if (this.dragged || this.hitTest(px, py) >= 0) {
        this.dragged = false;
        return;
      }
      const [x, y] = this.field.toField(px, py);
      this.addPoint(snap(clampField(x)), snap(clampField(y)));
    });

    canvas.addEventListener('contextmenu', (e) => {
      if (!this.active) return;
      const [px, py] = this.canvasPoint(e);
      const hit = this.hitTest(px, py);
      if (hit >= 0) {
        e.preventDefault();
        this.points.splice(hit, 1);
        this.refresh();
      }
    });
  }

  // ------------------------------------------------------------------
  // model
  // ------------------------------------------------------------------

  addPoint(x: number, y: number): void {
    this.points.push({ x, y, kind: 'point', theta: 0, forwards: true, maxSpeed: 127 });
    this.refresh();
  }

  clear(): void {
    this.points = [];
    this.refresh();
  }

  /** sync the field overlay, the list UI and the generated code */
  refresh(): void {
    this.field.plannerPoints = this.points;
    this.renderList();
    this.renderCode();
  }

  // ------------------------------------------------------------------
  // C++ generation
  // ------------------------------------------------------------------

  generateCpp(): string {
    if (this.points.length === 0) {
      return '// Click the field to add waypoints.\n// The C++ for your path appears here.';
    }

    const [start, ...rest] = this.points;
    const lines: string[] = [
      '// Path generated by Odyssey Simulator',
      `// ${this.points.length} waypoint${this.points.length === 1 ? '' : 's'}`,
      '',
      `chassis.setPose(${fmt(start.x)}, ${fmt(start.y)}, ${fmt(start.theta)});`,
    ];

    for (const p of rest) {
      lines.push('');
      const params: string[] = [];
      if (!p.forwards) params.push('.forwards = false');
      if (p.maxSpeed !== 127) params.push(`.maxSpeed = ${fmt(p.maxSpeed)}`);
      const paramStr = params.length > 0 ? `, {${params.join(', ')}}` : '';

      if (p.kind === 'pose') {
        lines.push(
          `chassis.moveToPose(${fmt(p.x)}, ${fmt(p.y)}, ${fmt(p.theta)}, ${this.timeout}${paramStr});`,
        );
      } else {
        lines.push(`chassis.moveToPoint(${fmt(p.x)}, ${fmt(p.y)}, ${this.timeout}${paramStr});`);
      }
      lines.push('chassis.waitUntilDone();');
    }

    return lines.join('\n');
  }

  /** the same path as a runnable simulator program */
  buildProgram(): (chassis: Chassis) => Promise<void> {
    const points = this.points.map((p) => ({ ...p }));
    const timeout = this.timeout;
    return async (chassis: Chassis) => {
      const [start, ...rest] = points;
      chassis.setPose(start.x, start.y, start.theta);
      for (const p of rest) {
        const params = { forwards: p.forwards, maxSpeed: p.maxSpeed };
        if (p.kind === 'pose') {
          await chassis.moveToPose(p.x, p.y, p.theta, timeout, params, false);
        } else {
          await chassis.moveToPoint(p.x, p.y, timeout, params, false);
        }
      }
    };
  }

  // ------------------------------------------------------------------
  // list + code UI
  // ------------------------------------------------------------------

  private rowInputs: { x: HTMLInputElement; y: HTMLInputElement }[] = [];

  private updateRowInputs(index: number): void {
    const row = this.rowInputs[index];
    if (!row) return;
    row.x.value = fmt(this.points[index].x);
    row.y.value = fmt(this.points[index].y);
  }

  private renderList(): void {
    this.listEl.innerHTML = '';
    this.rowInputs = [];

    if (this.points.length === 0) {
      const empty = document.createElement('div');
      empty.className = 'path-empty';
      empty.textContent = 'No waypoints yet — click the field to add the start point.';
      this.listEl.append(empty);
      return;
    }

    this.points.forEach((p, i) => {
      const row = document.createElement('div');
      row.className = 'path-row';
      const isStart = i === 0;

      const badge = document.createElement('span');
      badge.className = `path-badge${isStart ? ' start' : ''}`;
      badge.textContent = isStart ? 'S' : String(i);
      row.append(badge);

      const num = (value: number, step: number, title: string, onInput: (v: number) => void) => {
        const input = document.createElement('input');
        input.type = 'number';
        input.step = String(step);
        input.value = fmt(value);
        input.title = title;
        input.className = 'mono';
        input.addEventListener('input', () => {
          const v = Number(input.value);
          if (Number.isFinite(v)) {
            onInput(v);
            this.renderCode();
          }
        });
        row.append(input);
        return input;
      };

      const xInput = num(p.x, 0.5, 'x, inches', (v) => (p.x = clampField(v)));
      const yInput = num(p.y, 0.5, 'y, inches', (v) => (p.y = clampField(v)));
      this.rowInputs[i] = { x: xInput, y: yInput };

      if (isStart) {
        const label = document.createElement('span');
        label.className = 'path-kind-label';
        label.textContent = 'start pose';
        row.append(label);
      } else {
        const kind = document.createElement('select');
        kind.title = 'Motion used to reach this point';
        kind.innerHTML = '<option value="point">Point</option><option value="pose">Pose</option>';
        kind.value = p.kind;
        kind.addEventListener('change', () => {
          p.kind = kind.value as PathPoint['kind'];
          theta.disabled = p.kind !== 'pose';
          this.field.plannerPoints = this.points;
          this.renderCode();
        });
        row.append(kind);
      }

      const theta = num(p.theta, 15, 'heading, compass degrees', (v) => (p.theta = v));
      theta.classList.add('path-theta');
      if (!isStart) theta.disabled = p.kind !== 'pose';

      if (!isStart) {
        const rev = document.createElement('label');
        rev.className = 'path-rev';
        rev.title = 'Drive backwards into this point';
        const check = document.createElement('input');
        check.type = 'checkbox';
        check.checked = !p.forwards;
        check.addEventListener('change', () => {
          p.forwards = !check.checked;
          this.renderCode();
        });
        rev.append(check, document.createTextNode('rev'));
        row.append(rev);
      }

      const del = document.createElement('button');
      del.className = 'btn small icon-only path-del';
      del.setAttribute('aria-label', `Delete waypoint ${isStart ? 'S' : i}`);
      del.innerHTML = '<svg aria-hidden="true"><use href="#i-x" /></svg>';
      del.addEventListener('click', () => {
        this.points.splice(i, 1);
        this.refresh();
      });
      row.append(del);

      this.listEl.append(row);
    });
  }

  private renderCode(): void {
    this.codeEl.textContent = this.generateCpp();
  }
}

function clampField(v: number): number {
  return Math.max(-72, Math.min(72, v));
}

/** snap to a half-inch so the generated code has clean coordinates */
function snap(v: number): number {
  return Math.round(v * 2) / 2;
}
